### ISSUE TITLE
Opacity doesn't change if icons are enabled on the desktop

### ISSUE THREAD

**Issue by k9rosie** [rockon999/dynamic-panel-transparency#25] opened 2016-04-28 03:32 UTC
Running Gnome 3.20 on Arch Linux. If icons are enabled on the desktop in the tweak settings then the opacity will stay the same regardless of whether or not a window is maximized or minimized.

**Comment by ccrisan** [comment] 2016-04-29 16:25
I am also experiencing this issue. I'd be happy to provide further details if needed.

**Comment by rockon999** [comment] 2016-04-30 00:10
Hi! I'll start debugging this on my end. In the meantime, if you could also send me logs that would be great. After enabling icons and attempting to toggle the panel enter **journalctl --since "20 seconds ago"** in terminal. That will give you any errors from the extension. Thanks!

**Comment by rockon999** [comment] 2016-04-30 00:19
@k9rosie @ccrisan Hi! It seems I'm going to have to debug my system first. Nautilus crashes with desktop icons enabled for me.

**Comment by rockon999** [comment] 2016-04-30 00:59
@k9rosie @ccrisan I've reproduced the bug and have pushed a patch. The latest in the git repository should fix this issue. If you have the time to test the changes and report back I'd greatly appreciate it!

**Comment by k9rosie** [comment] 2016-04-30 04:43
Seems to be working now with the latest change

**Comment by ccrisan** [comment] 2016-04-30 07:05
I confirm the fix is effective. @rockon999 thanks for your work!

**Comment by joaoherberto** [comment] 2016-04-30 17:13
Git version works for me as well, nice job!

**Comment by rockon999** [comment] 2016-04-30 18:36
This'll go up on Gnome Extensions as soon as possible.

**Comment by rockon999** [comment] 2016-05-20 01:41
Fixed in v9.

**Closed** 2016-05-20 01:41 UTC
Labels: bug
